dist: trusty
language: node_js
cache:
    bundler: true
    directories:
        - node_modules
addons:
    chrome: stable
node_js:
 - 6

before_install:
    - export DISPLAY=:99.0
install: make dev
before_script: make serve_bg
script: make check
sudo: false
